In [2]:
import numpy as np

In [3]:
a = np.array([101,102,103,104,105,106])
a

array([101, 102, 103, 104, 105, 106])

In [4]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',

In [29]:
# creating a two-dimensional array
arr = np.array([[3,4],[2,5]])
arr.shape

(2, 2)

In [31]:
arr

array([[3, 4],
       [2, 5]])

In [28]:
# Indexing multidimensional
arr[0][1]

4

In [43]:
# write a np.array of shape(2,3,4)
c = np.array([[[1,21,3,44],[0,-1,0.,4],[1,-1.,2.,10]],[[1,8,3,4],[9,-1,0.,4],[20,-1.,2.,0]]])

In [47]:
c

array([[[ 1., 21.,  3., 44.],
        [ 0., -1.,  0.,  4.],
        [ 1., -1.,  2., 10.]],

       [[ 1.,  8.,  3.,  4.],
        [ 9., -1.,  0.,  4.],
        [20., -1.,  2.,  0.]]])

In [50]:
c[1][2][0]

20.0

In [51]:
c[0][0][1]

21.0

In [56]:
# Creating an array
b = np.array([[1,2],[3,4]])
# Changing the value of an element in list or assigning
b[1][0]=4
b

array([[1, 2],
       [4, 4]])

In [57]:
# Creating an array with complex data type
np.array([0,4,-4],dtype=complex)

array([ 0.+0.j,  4.+0.j, -4.+0.j])

In [59]:
# Creating an array with shape(2,3) - random values
np.empty((2,3))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [1.95820760e-306, 1.89146896e-307, 7.56571288e-307]])

In [61]:
# Creating an array with values as zero in shape (4,2,3)
# by default data type is float here
x = np.zeros((4,2,3))
x.shape

(4, 2, 3)

In [63]:
# Printing the array
x

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [67]:
# Creating an array with zeroes and integer data type
y = np.zeros((2,5), dtype=int)
y

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [70]:
# Creating an array with all values as 1 with the same shape
np.ones_like(y)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [71]:
# Creating an array with all values as 0 (datatype-float) with the same shape
np.zeros_like(y)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [72]:
# Creating an list with range 7
list(range(7))

[0, 1, 2, 3, 4, 5, 6]

In [74]:
# Generating a sequence starting with 1.5 with width as 0.5 and excluding value 4
np.arange(1.5,4,0.5)

array([1.5, 2. , 2.5, 3. , 3.5])

In [75]:
# Creating an array of 20 elements starting from 1 and ending at 10 with shape(4,5)
np.linspace(1,10,20).reshape(4,5)

array([[ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684],
       [ 3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789],
       [ 5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895],
       [ 8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ]])

In [76]:
# Creating an evenly spaced array of five numbers between 10 and 20 inclusive
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [81]:
# Creating an evenly spaced array of 10 numbers between 10 and 20
# Also mentioning the spacing between the values in interval using retstep=True
x = np.linspace(10,20,10, retstep=True)
x

(array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
        15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ]),
 1.1111111111111112)

In [83]:
# Here endpoint = False omits the final point in the sequence
x = np.linspace(0,5,10, endpoint=False)
x

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [85]:
# Initializing an array from a function
def fun(i,j):
    return 2*i*j

np.fromfunction(fun,(4,3))


array([[ 0.,  0.,  0.],
       [ 0.,  2.,  4.],
       [ 0.,  4.,  8.],
       [ 0.,  6., 12.]])

In [86]:
# Initializing an array from a one line function
np.fromfunction(lambda i,j: 2*i*j,(4,3))

array([[ 0.,  0.,  0.],
       [ 0.,  2.,  4.],
       [ 0.,  4.,  8.],
       [ 0.,  6., 12.]])

In [90]:
# Creating a "comb" of values in an array of length N for which every nth element is one but with zeros everywhere else
N, n = 20, 5
def fun(i):
    return (i%n ==0)*1

comb = np.fromfunction(fun,(N,),dtype=int)
comb


array([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [99]:
# ndarray attributes for introspection
a = np.array(((1,0,1),(0,1,0)))
a.shape # returns axis dimensions

(2, 3)

In [94]:
a.ndim # rank (no of dimensions)

2

In [101]:
a.size # total no of elements

6

In [105]:
a = np.array([[[1,2],[2,3]],[[2,1],[1,2]],[[2,1],[1,2]]])
a.shape # (depth,length,width)

(3, 2, 2)

In [106]:
a.data # buffer in memory containing the actual elements of the array

In [107]:
a.dtype # array's data type

dtype('int32')

In [108]:
a.itemsize # the size in bytes of each element

4

In [110]:
# Universal Functions
x = np.linspace(1,5,5)
x

array([1., 2., 3., 4., 5.])

In [111]:
x**3 # cube

array([  1.,   8.,  27.,  64., 125.])

In [112]:
np.sqrt(x-1) 

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [113]:
y = np.exp(-np.linspace(0,2,5))
np.sin(x-y)

array([ 0.        ,  0.98431873,  0.48771645, -0.59340065, -0.98842844])

In [114]:
# Matrix multiplication in numpy - elemeentwise multiplication
a = np.array(((1,2),(2,1)))
b = a
a*b

array([[1, 4],
       [4, 1]])

In [117]:
b = a.T # transpose
b

array([[1, 2],
       [2, 1]])

In [118]:
np.matmul(a,b) # matrix multiplication

array([[5, 4],
       [4, 5]])

In [119]:
np.dot(a,b)  # matrix multiplication

array([[5, 4],
       [4, 5]])

In [120]:
a = np.array([[1,2,3],[2,3,4]])
b = np.array([1,2])
np.dot(b,a)

array([ 5,  8, 11])

In [122]:
a>3 #comparison

array([[False, False, False],
       [False, False,  True]])

In [123]:
(a<3) | (a>4) # or operator

array([[ True,  True, False],
       [ True, False, False]])