In [1]:
import numpy as np

In [2]:
a = np.array([101,102,103,104,105,106])
a

array([101, 102, 103, 104, 105, 106])

In [3]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',

In [4]:
# creating a two-dimensional array
arr = np.array([[3,4],[2,5]])
arr.shape

(2, 2)

In [5]:
arr

array([[3, 4],
       [2, 5]])

In [6]:
# Indexing multidimensional
arr[0][1]

4

In [7]:
# write a np.array of shape(2,3,4)
c = np.array([[[1,21,3,44],[0,-1,0.,4],[1,-1.,2.,10]],[[1,8,3,4],[9,-1,0.,4],[20,-1.,2.,0]]])

In [8]:
c

array([[[ 1., 21.,  3., 44.],
        [ 0., -1.,  0.,  4.],
        [ 1., -1.,  2., 10.]],

       [[ 1.,  8.,  3.,  4.],
        [ 9., -1.,  0.,  4.],
        [20., -1.,  2.,  0.]]])

In [9]:
c[1][2][0]

20.0

In [10]:
c[0][0][1]

21.0

In [11]:
# Creating an array
b = np.array([[1,2],[3,4]])
# Changing the value of an element in list or assigning
b[1][0]=4
b

array([[1, 2],
       [4, 4]])

In [12]:
# Creating an array with complex data type
np.array([0,4,-4],dtype=complex)

array([ 0.+0.j,  4.+0.j, -4.+0.j])

In [13]:
# Creating an array with shape(2,3) - random values
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
# Creating an array with values as zero in shape (4,2,3)
# by default data type is float here
x = np.zeros((4,2,3))
x.shape

(4, 2, 3)

In [15]:
# Printing the array
x

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [16]:
# Creating an array with zeroes and integer data type
y = np.zeros((2,5), dtype=int)
y

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [17]:
# Creating an array with all values as 1 with the same shape
np.ones_like(y)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [18]:
# Creating an array with all values as 0 (datatype-float) with the same shape
np.zeros_like(y)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [19]:
# Creating an list with range 7
list(range(7))

[0, 1, 2, 3, 4, 5, 6]

In [20]:
# Generating a sequence starting with 1.5 with width as 0.5 and excluding value 4
np.arange(1.5,4,0.5)

array([1.5, 2. , 2.5, 3. , 3.5])

In [21]:
# Creating an array of 20 elements starting from 1 and ending at 10 with shape(4,5)
np.linspace(1,10,20).reshape(4,5)

array([[ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684],
       [ 3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789],
       [ 5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895],
       [ 8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ]])

In [22]:
# Creating an evenly spaced array of five numbers between 10 and 20 inclusive
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [23]:
# Creating an evenly spaced array of 10 numbers between 10 and 20
# Also mentioning the spacing between the values in interval using retstep=True
x = np.linspace(10,20,10, retstep=True)
x

(array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
        15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ]),
 1.1111111111111112)

In [24]:
# Here endpoint = False omits the final point in the sequence
x = np.linspace(0,5,10, endpoint=False)
x

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [25]:
# Initializing an array from a function
def fun(i,j):
    return 2*i*j

np.fromfunction(fun,(4,3))


array([[ 0.,  0.,  0.],
       [ 0.,  2.,  4.],
       [ 0.,  4.,  8.],
       [ 0.,  6., 12.]])

In [26]:
# Initializing an array from a one line function
np.fromfunction(lambda i,j: 2*i*j,(4,3))

array([[ 0.,  0.,  0.],
       [ 0.,  2.,  4.],
       [ 0.,  4.,  8.],
       [ 0.,  6., 12.]])

In [27]:
# Creating a "comb" of values in an array of length N for which every nth element is one but with zeros everywhere else
N, n = 20, 5
def fun(i):
    return (i%n ==0)*1

comb = np.fromfunction(fun,(N,),dtype=int)
comb


array([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [28]:
# ndarray attributes for introspection
a = np.array(((1,0,1),(0,1,0)))
a.shape # returns axis dimensions

(2, 3)

In [29]:
a.ndim # rank (no of dimensions)

2

In [30]:
a.size # total no of elements

6

In [31]:
a = np.array([[[1,2],[2,3]],[[2,1],[1,2]],[[2,1],[1,2]]])
a.shape # (depth,length,width)

(3, 2, 2)

In [32]:
a.data # buffer in memory containing the actual elements of the array

In [33]:
a.dtype # array's data type

dtype('int32')

In [34]:
a.itemsize # the size in bytes of each element

4

In [35]:
# Universal Functions
x = np.linspace(1,5,5)
x

array([1., 2., 3., 4., 5.])

In [36]:
x**3 # cube

array([  1.,   8.,  27.,  64., 125.])

In [37]:
np.sqrt(x-1) 

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [38]:
y = np.exp(-np.linspace(0,2,5))
np.sin(x-y)

array([ 0.        ,  0.98431873,  0.48771645, -0.59340065, -0.98842844])

In [39]:
# Matrix multiplication in numpy - elemeentwise multiplication
a = np.array(((1,2),(2,1)))
b = a
a*b

array([[1, 4],
       [4, 1]])

In [40]:
b = a.T # transpose
b

array([[1, 2],
       [2, 1]])

In [41]:
np.matmul(a,b) # matrix multiplication

array([[5, 4],
       [4, 5]])

In [42]:
np.dot(a,b)  # matrix multiplication

array([[5, 4],
       [4, 5]])

In [43]:
a = np.array([[1,2,3],[2,3,4]])
b = np.array([1,2])
np.dot(b,a)

array([ 5,  8, 11])

In [44]:
a>3 #comparison

array([[False, False, False],
       [False, False,  True]])

In [45]:
(a<3) | (a>4) # or operator

array([[ True,  True, False],
       [ True, False, False]])

In [46]:
# Creating an NxN magic square where N is odd
N = 3
mgsq = np.zeros((N,N), dtype=int)

n = 1
i,j=0,N//2

while n <= N**2:
    mgsq[i,j] = n
    n += 1
    newi, newj = (i-1)%N, (j+1)%N
    if mgsq[newi,newj]:
        i += 1
    else:
        i,j = newi,newj

mgsq

array([[8, 1, 6],
       [3, 5, 7],
       [4, 9, 2]])

In [48]:
a = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
b = a.flatten() # creates a independent, flatten copy of a
b # flatten - method of an ndarray object - occupies memory

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
c = a.ravel() # ravel is faster than flatten as it is an library-level function 
c  # ravel doesn't occupy memory

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
a = np.linspace(1,8,8)
a

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [52]:
a.resize(2,2,2) # reshapes a in place, with its elements reshaped as required
a

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [57]:
a = np.linspace(1,16,16)
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16.])

In [61]:
a = a.reshape(2,2,4)
a

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]])

In [63]:
a.T # Transpose

array([[[ 1.,  9.],
        [ 5., 13.]],

       [[ 2., 10.],
        [ 6., 14.]],

       [[ 3., 11.],
        [ 7., 15.]],

       [[ 4., 12.],
        [ 8., 16.]]])

Merging and splitting arrays

In [70]:
a = np.array([0,0,0,0])
b = np.array([1,1,1,1])
c = np.array([2,2,2,2])
x = np.vstack((a,b,c)) # np.vstack - stack arrays vertically (in rows)
x

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2]])

In [67]:
x = np.hstack((a,b,c)) # np.hstack - stack arrays horizontally (in cols)
x

array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2])

In [69]:
x = np.dstack((a,b,c)) # np.dstack - stack arrays depthwise (along third axis)
x

array([[[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [72]:
# Indexing and Slicing an Array
a = np.linspace(10,16,6)
a

array([10. , 11.2, 12.4, 13.6, 14.8, 16. ])

In [75]:
a[1:5:2] # a stride of 2 between 1 and 5

array([11.2, 13.6])

In [77]:
a[2::3] # a stride of 3 starting from 2 to end

array([12.4, 16. ])

In [80]:
a = np.linspace(1,12,12).reshape(4,3)
a

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [89]:
a[:2] # first two rows

array([[1., 2., 3.],
       [4., 5., 6.]])

In [82]:
a[:,1] # second col

array([ 2.,  5.,  8., 11.])

In [90]:
a[:,1] = 0 # all elements in second col to zero
a

array([[ 1.,  0.,  3.],
       [ 4.,  0.,  6.],
       [ 7.,  0.,  9.],
       [10.,  0., 12.]])

In [92]:
a = np.linspace(1,10,10)
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [94]:
ia = [1,4,5]
a[ia] # array from specified indexes

array([2., 5., 6.])

In [95]:
a = np.linspace(1,12,12).reshape(4,3)
a

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [97]:
ia = np.array(((1,0),(2,1)))
ja = np.array(((0,1),(1,2)))
a[ia,ja]

array([[4., 2.],
       [8., 6.]])

In [98]:
# Adding an axis
a = np.linspace(1,4,4).reshape(2,2)
a.shape

(2, 2)

In [99]:
b = a[::, np.newaxis] # newaxis
b.shape

(2, 1, 2)

In [101]:
# Mesh - evaluates a multidimesnsional function on a grid of points
x = np.linspace(0,5,6)
y = np.linspace(0,3,4)
X,Y = np.meshgrid(x,y)
X

array([[0., 1., 2., 3., 4., 5.],
       [0., 1., 2., 3., 4., 5.],
       [0., 1., 2., 3., 4., 5.],
       [0., 1., 2., 3., 4., 5.]])

In [102]:
Y

array([[0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3.]])

In [108]:
X,Y = np.meshgrid(x,y,sparse=True) # conserves memory
X,Y

(array([[0., 1., 2., 3., 4., 5.]]),
 array([[0.],
        [1.],
        [2.],
        [3.]]))

Broadcasting

In [117]:
a = np.array((0,1,2))
b = np.array((5,5,5))
a+b

array([5, 6, 7])

In [118]:
M = np.random.randint(10,size=(3,3))
M

array([[0, 4, 7],
       [3, 1, 7],
       [9, 7, 7]])

In [119]:
M+a

array([[0, 5, 9],
       [3, 2, 9],
       [9, 8, 9]])

In [122]:
# broadcast across the second dimension
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]
print(a)
print(b)
a+b

[0 1 2]
[[0]
 [1]
 [2]]


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [147]:
M = np.ones((2,3))
a = np.arange(3)
print(M.shape)
a.shape

(2, 3)


(3,)

In [148]:
M

array([[1., 1., 1.],
       [1., 1., 1.]])

In [149]:
a

array([0, 1, 2])

In [150]:
print(M+a)
(M+a).shape

[[1. 2. 3.]
 [1. 2. 3.]]


(2, 3)

In [151]:
a = np.arange(3).reshape((3,1))
b = np.arange(3)
print(a)
print(a.shape)
print(b)
b.shape

[[0]
 [1]
 [2]]
(3, 1)
[0 1 2]


(3,)

In [152]:
print(a+b)
(a+b).shape

[[0 1 2]
 [1 2 3]
 [2 3 4]]


(3, 3)

Maximum and Minimum Values

In [162]:
a = np.random.randint(-5,10,size=(3,4))

In [163]:
a

array([[ 7,  1, -1,  9],
       [ 3,  2,  0,  7],
       [ 6,  0,  4, -4]])

In [167]:
np.argmin(a) # produces index value of min of the array after flatten

11

In [170]:
np.argmax(a) # produces index value of max of the array after flatten

3

In [172]:
print(a.max(axis=0)) # max in each col
print(a.min(axis=1)) # min in each row

[7 2 4 9]
[-1  0 -4]


Sorting an Array

In [188]:
a = np.random.randint(-5,10,size=(6))
a.sort()
a

array([-4, -1,  4,  7,  8,  9])

In [192]:
b = np.random.randint(-10,20,size=(3,3))
b

array([[17,  6, 19],
       [ 8, 17, -9],
       [15, -8, -9]])

In [193]:
b.sort() # sort numbers along each row
b

array([[ 6, 17, 19],
       [-9,  8, 17],
       [-9, -8, 15]])

In [196]:
a = np.random.randint(-3,13,size=(5))
a

array([ 8, -1,  4, 12, -3])

In [200]:
print(np.argsort(a)) # gives sort array with index values
print(a[np.argsort(a)])

[4 1 2 0 3]
[-3 -1  4  8 12]


In [208]:
a.sort()
a

array([-3, -1,  4,  8, 12])

In [213]:
np.searchsorted(a,-2) # In a sorted array, we get the index value 
# where we have to place the value required

1

# Statistics

Maxima and Minima

In [217]:
a = np.sqrt(np.linspace(-2,2,4))
a

C:\Users\sivar\AppData\Local\Temp\ipykernel_16296\1155619188.py:1: RuntimeWarning: invalid value encountered in sqrt
  a = np.sqrt(np.linspace(-2,2,4))


array([       nan,        nan, 0.81649658, 1.41421356])

In [218]:
np.min(a),np.max(a)

(nan, nan)

In [219]:
np.nanmin(a),np.nanmax(a)

(0.8164965809277259, 1.4142135623730951)

In [220]:
np.nanargmin(a),np.nanargmax(a)

(2, 3)

In [225]:
b = np.array([1,-5,6,2])
c = np.array([0,np.nan,-1,3])
print('min',np.fmin(b,c)) # Compares both arrays element wise and gives the min
print('max',np.fmax(b,c)) # Compares both arrays element wise and gives the max

min [ 0. -5. -1.  2.]
max [ 1. -5.  6.  3.]


Percentiles

In [228]:
a = np.array([[0,0.6,1.2],[1.8,2.4,3.0]])
a

array([[0. , 0.6, 1.2],
       [1.8, 2.4, 3. ]])

In [235]:
# compares all the values in a and prints required percent value
print('0 percent:   ',np.percentile(a,0))   # 0 percent i.e. least
print('100 percent: ',np.percentile(a,100)) # 100 percent i.e. max
print('75 percent:  ',np.percentile(a,75))   # 75 percent
print('25 percent:  ',np.percentile(a,25))  # 25 percent

0 percent:    0.0
100 percent:  3.0
75 percent:   2.25
25 percent:   0.75


In [237]:
print('50 percent col wise:',np.percentile(a,50,axis=0)) # 50 percent - col wise
print('50 percent row wise:',np.percentile(a,50,axis=1)) # 50 percent - row wise

50 percent col wise: [0.9 1.5 2.1]
50 percent row wise: [0.6 2.4]


Sample Statistics

In [247]:
x = np.array([1,4,9,16])
np.mean(x) # arithmetic mean 

7.5

In [248]:
np.median(x) # arithmetic median

6.5

In [249]:
np.average(x, weights=[0.3,0,1,0]) # weighted average

7.153846153846154

In [246]:
np.std(x) # standard deviation

5.678908345800274

In [245]:
np.std(x,ddof=1) # delta degrees of freedom

6.557438524302

In [252]:
np.var(x) # variance

32.25

In [253]:
np.sqrt(np.var(x)) # sqrt of variance - standard deviation

5.678908345800274

In [260]:
a = np.random.randint(0,20,size=(5,4))
a

array([[19, 12,  9,  5],
       [ 8,  9, 19,  2],
       [11,  0,  2, 11],
       [ 5,  4,  9,  3],
       [19,  1, 14, 18]])

In [262]:
np.cov(a) # covariance matrix

array([[ 34.91666667,   4.5       ,   4.        ,   0.91666667,
          1.33333333],
       [  4.5       ,  49.66666667, -26.66666667,  17.83333333,
        -10.33333333],
       [  4.        , -26.66666667,  34.        ,  -6.66666667,
         41.        ],
       [  0.91666667,  17.83333333,  -6.66666667,   6.91666667,
          2.        ],
       [  1.33333333, -10.33333333,  41.        ,   2.        ,
         68.66666667]])

In [265]:
np.corrcoef(a) # corelation matrix

array([[ 1.        ,  0.10805967,  0.11609249,  0.05898569,  0.02723011],
       [ 0.10805967,  1.        , -0.64892838,  0.96216953, -0.17694364],
       [ 0.11609249, -0.64892838,  1.        , -0.43473125,  0.84853823],
       [ 0.05898569,  0.96216953, -0.43473125,  1.        ,  0.09177166],
       [ 0.02723011, -0.17694364,  0.84853823,  0.09177166,  1.        ]])

Special Distributions

In [269]:
np.random.randint(1,20,10) # 10 random integers from 1 to 20

array([11,  4,  9,  1, 11, 12, 10, 11,  7,  1])

In [271]:
np.random.random_sample((2,3)) # random floating point numbers

array([[0.91330145, 0.76582638, 0.97364827],
       [0.40236064, 0.55277195, 0.30636063]])

In [272]:
np.random.randint(4) # random integer from 0 to 4

3

In [277]:
np.random.randint(1,12,size=(3,5)) # 3x5 matrix of integers from 1 to 12

array([[ 1, 11,  7,  1,  5],
       [ 2,  6,  2,  9,  9],
       [ 8,  1,  1, 10,  2]])

In [278]:
np.random.normal() # random samples from normal distribution
# where mean = loc and std = scale in range 0 to 1 by default

0.9425030467360929

In [279]:
np.random.normal(scale=5,size=3)

array([-3.0350714 , -2.2956163 , -0.08502096])