In [1]:
# Importing numpy library
import numpy as np

In [9]:
# function to create a new matrix
def newmatrix(n):
    Matrix = []
    for i in range(0,n):
        t = []
        for j in range(0,n):
            print('Please enter',i,j,'th value: ')
            t.append(int(input()))
        Matrix.append(t)
    return Matrix

# dimension(size) of the matrix
n = int(input('Dim of matrix: '))
print('\n---Matrix values---')
mat = newmatrix(n)

print('\nThe matrix is: ',mat) # displaying the matrix

# converting the matrix(list) to numoy array      
np_arr = np.array(mat)

# computing the eigen values and eigen vectors
e_val, e_vectors = np.linalg.eig(np_arr)

# displaying the eigen values and eigen vectors
print('\nEigen values: ',e_val)
print('\nEigen vectors: ',e_vectors)

Dim of matrix: 3

---Matrix values---
Please enter 0 0 th value: 
2
Please enter 0 1 th value: 
5
Please enter 0 2 th value: 
3
Please enter 1 0 th value: 
4
Please enter 1 1 th value: 
5
Please enter 1 2 th value: 
6
Please enter 2 0 th value: 
2
Please enter 2 1 th value: 
4
Please enter 2 2 th value: 
9

The matrix is:  [[2, 5, 3], [4, 5, 6], [2, 4, 9]]

Eigen values:  [14.06075946 -1.31234342  3.25158397]

Eigen vectors:  [[-0.42203477 -0.8128918  -0.64222523]
 [-0.62265404  0.57857514 -0.50614507]
 [-0.65892989 -0.06676629  0.57564218]]


In [25]:
def newmatrix(r,c):
    Matrix = []
    for i in range(0,r):
        t = []
        for j in range(0,c):
            print('Please enter',i,j,'th value: ')
            t.append(int(input()))
            Matrix.append(t)
    return Matrix

row = int(input('Rows of Matrix: '))
col = int(input('Cols of Matrix: '))

mat = newmatrix(row,col)

# Converting the matrix into numpy array
A = np.array(mat)

# A*A' and A'*A
v = np.dot(A.T, A)
u = np.dot(A, A.T)

# Computing eigenvalues and eigenvectors
eval_v, evec_v = np.linalg.eig(v)
eval_u, evec_u = np.linalg.eig(u)

# Sorting eigenvalues and then adjusting eigenvectors
sort_v = np.argsort(eval_v)[::-1]
sort_u = np.argsort(eval_u)[::-1]

eval_v = eval_v[sort_v]
eval_u = eval_u[sort_u]

evec_v = evec_v[:, sort_v]
evec_u = evec_u[:, sort_u]

# singular values
singular_values = np.sqrt(eval_v)

# Matrices U and V
U = evec_u
V = evec_v

# Sigma
m, n = A.shape
lam = np.zeros((m, n))
for i in range(min(m, n)):
    lam[i, i] = singular_values[i]

# SVD components
print("\nU (left singular vectors): ",U)
print("\nlam (singular values): ",lam)
print("\nV^T (transpose of right singular vectors): ",V.T)


SVD = U@lam@V.T
print('SVD: ',SVD)
SVD

Rows of Matrix: 2
Cols of Matrix: 3
Please enter 0 0 th value: 
1
Please enter 0 1 th value: 
2
Please enter 0 2 th value: 
5
Please enter 1 0 th value: 
3
Please enter 1 1 th value: 
6
Please enter 1 2 th value: 
4

U (left singular vectors):  [[-3.14926934e-01  4.83894988e-01  5.77785464e-17 -1.01454111e-33
  -3.32879030e-01 -8.10863384e-01]
 [-3.14926934e-01  4.83894988e-01 -7.15551885e-17  5.21996080e-33
   8.12112546e-01  4.88349901e-01]
 [-3.14926934e-01  4.83894988e-01  1.37766421e-17 -4.20541969e-33
  -4.79233516e-01  3.22513483e-01]
 [-4.83894988e-01 -3.14926934e-01 -8.16496581e-01  3.23523708e-17
   2.35202765e-16  2.46923003e-16]
 [-4.83894988e-01 -3.14926934e-01  4.08248290e-01 -7.07106781e-01
   2.56937335e-16  2.49714186e-16]
 [-4.83894988e-01 -3.14926934e-01  4.08248290e-01  7.07106781e-01
   2.56937335e-16  2.49714186e-16]]

lam (singular values):  [[1.58535722e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 4.65448684e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000

array([[-2.33812201, -4.67624402, -1.63276677],
       [-2.33812201, -4.67624402, -1.63276677],
       [-2.33812201, -4.67624402, -1.63276677],
       [-2.12912797, -4.25825568, -6.19145158],
       [-2.12912781, -4.25825576, -6.19145158],
       [-2.12912781, -4.25825576, -6.19145158]])